name: Deploy Blazor WebAssembly to Azure Static Web App

on:
  push:
    branches:
      - main  # Change if your main branch is different
  workflow_dispatch:  # Allow manual deployment if needed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' 

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Blazor WebAssembly
        run: dotnet publish -c Release --output publish_output

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "publish_output/wwwroot"  # Correct output for Blazor WASM
          api_location: ""  # Leave blank for no API
          output_location: ""  # Not needed for Blazor
